from typing import List, Tuple, Union
from datetime import datetime

Row = Tuple[Union[int, float, bool, str, bytes], ...]


class Cursor:
    description: List[Tuple[str, ...]]
    def execute(self, *args: str, **kwargs: Union[str, datetime]) -> None: ...
    def fetchall(self) -> List[Row]: ...


class Connection:
    def __init__(self, connection_string: str) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def cursor(self) -> Cursor: ...


class connect(Connection):
    def __init__(self, connection_string: str) -> None: ...
