#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}

if (($# != 0))
then
    printf 'Usage:\n\t%s\n' "$me"
    exit 1
fi

mydir=${0%/*}
src="$mydir/../src"

cd "$src"

username=$USER
displayname=${DISPLAYNAME:-$(finger "$USER" | grep --only-matching --perl-regexp '(?<=Name: ).*$')}

grep --files-with-matches --fixed-strings --null --recursive 'Ankit Pati' . | xargs --null --no-run-if-empty sed --in-place "s/Ankit Pati/$displayname/g"
grep --files-with-matches --fixed-strings --null --recursive ankit.pati . | xargs --null --no-run-if-empty sed --in-place "s/ankit\\.pati/$username/g"
grep --files-with-matches --fixed-strings --null --recursive ankitpati . | xargs --null --no-run-if-empty sed --in-place "s/ankitpati/${username//.}/g"
