#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}

if (($# != 0))
then
    printf 'Usage:\n\t%s\n' "$me"
    exit 1
fi

mydir=${0%/*}
src="$mydir/../src"

cd "$src"

username=$USER
displayname=${DISPLAYNAME:-$(finger "$USER" | grep --only-matching --perl-regexp '(?<=Name: ).*$')}

declare -a grep_command=(
    grep
        --files-with-matches
        --fixed-strings
        --null
        --recursive
)

declare -a xargs_sed_command=(
    xargs
        --no-run-if-empty
        --null
            sed
                --in-place
)

"${grep_command[@]}" 'Ankit Pati' . | "${xargs_sed_command[@]}" "s/Ankit Pati/$displayname/g"
"${grep_command[@]}" ankit.pati . | "${xargs_sed_command[@]}" "s/ankit\\.pati/$username/g"
"${grep_command[@]}" ankitpati . | "${xargs_sed_command[@]}" "s/ankitpati/${username//.}/g"
