#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}
mydir=${0%/*}

if (($# != 0))
then
    printf 'Usage: %s\n' "$me"
    exit 1
fi

mapfile -d '' spcfiles < <(find "$mydir/../src/" -type f -iname '*.spc' -print0)

for spcfile in "${spcfiles[@]}"
do
    mv "$spcfile" "$spcfile.tf"
    terraform fmt -- "$spcfile.tf"
    mv "$spcfile.tf" "$spcfile"
done
