#!/usr/bin/env bash

set -euo pipefail

me="$(basename "$0")"
mydir="$(dirname "$0")/"

if (($# != 0))
then
    printf 'Usage: %s\n' "$me"
    exit 1
fi

tidy -mciq --sort-attributes alpha --indent-spaces 4 -w 150 -xml -- \
    "$mydir/../src/.local/share/kxmlgui5/konsole/"{konsoleui,sessionui}.rc
