#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}
mydir=${0%/*}

if (($# != 0))
then
    printf 'Usage: %s\n' "$me"
    exit 1
fi

tidy \
    --indent-spaces 4 \
    --sort-attributes alpha \
    -clean \
    -indent \
    -modify \
    -quiet \
    -wrap 150 \
    -xml \
    -- \
    "$mydir/../src/.local/share/kxmlgui5/konsole/"{konsoleui,sessionui}.rc
