#!/usr/bin/env bash

set -euo pipefail

me="$(basename "$0")"
mydir="$(dirname "$0")/"

if [[ $# -ne 0 ]]
then
    echo "Usage: $me"
    exit 1
fi

mapfile -d '' jsonfiles < <(find "$mydir/../src/" -type f -iname '*.json' -print0)

for jsonfile in "${jsonfiles[@]}"
do
    jq -S --indent 4 . "$jsonfile" | sponge "$jsonfile"
done
