#!/usr/bin/env bash

set -euo pipefail

me="$(basename "$0")"
mydir="$(dirname "$0")/"

if (($# != 0))
then
    printf 'Usage: %s\n' "$me"
    exit 1
fi

mapfile -d '' jsonfiles < <(find "$mydir/../src/" -type f -iname '*.json' -print0)

for jsonfile in "${jsonfiles[@]}"
do
    jq --sort-keys --indent 4 . -- "$jsonfile" | sponge "$jsonfile"
done
