#!/usr/bin/env bash

set -euo pipefail

me="$(basename "$0")"
mydir="$(dirname "$0")/"

if (($# != 0))
then
    printf 'Usage: %s\n' "$me"
    exit 1
fi

dark_reader_json_file="$mydir/../src/.dark-reader.json"

jq \
    --sort-keys \
    --indent 4 \
    '
    .customThemes[0].url = (.customThemes[0:] | [.[].url] | flatten | sort) |
    .customThemes = [.customThemes[0]] |
    .siteList = (.siteList[0:] | sort) |
    .siteListEnabled = (.siteListEnabled[0:] | sort)
    ' \
    -- \
    "$dark_reader_json_file" \
    | \
    sponge "$dark_reader_json_file"
