#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}
mydir=${0%/*}

if (($# != 0))
then
    printf 'Usage: %s\n' "$me"
    exit 1
fi

mapfile -d '' jsonfiles < <(find "$mydir/../src/" -type f -iname '*.json' -print0)

for jsonfile in "${jsonfiles[@]}"
do
    jq \
        --indent 4 \
        --sort-keys \
        . \
        -- \
        "$jsonfile" \
        | \
        sponge "$jsonfile"
done
