#!/usr/bin/env bash

set -euo pipefail

# Usage:
#   ../tools/tidy-dark-reader-json-files [file-to-merge]...

me="$(basename "$0")"
mydir="$(dirname "$0")/"

dark_reader_json_files=("$mydir/../src/.dark-reader.json" "$@")

jq \
    --from-file "$mydir/$me.jq" \
    --indent 4 \
    --slurp \
    --sort-keys \
    -- \
    "${dark_reader_json_files[@]}" \
    | \
    sponge "${dark_reader_json_files[0]}"
